# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message_man',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datatime')),
                ('message_title', models.CharField(max_length=40)),
                ('message_txt', models.TextField(max_length=40)),
                ('message_sendname', models.CharField(max_length=150)),
                ('message_recivename', models.CharField(max_length=150)),
                ('message_status', models.IntegerField(default=1)),
            ],
        ),
    ]
